version: "3.8"
 
services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate && 
      python manage.py wait_for_db && 
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    links:
      - db
  db:
    image: "postgres:11"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres:
