version: "3.8"
 
services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate && 
      python manage.py wait_for_db && 
      gunicorn productimporter.wsgi:application -w 2 -b :8000 --reload"
    env_file:
      - .env
    links:
      - db
      - rabbitmq
  db:
    image: "postgres:11"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
  celery:
    restart: on-failure
    build:
      context: .
    command: celery -A productimporter worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - app
volumes:
  postgres:
